spring.application.name=shop

spring.datasource.url=jdbc:postgresql://localhost:5432/shop_db
spring.datasource.username=postgres
spring.datasource.password=Taha1060
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
jwt.secret=mysupersecretkeymysupersecretkeymysupersecretkey
jwt.expire=86400000
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=houman5182@gmail.com
spring.mail.password=mtxvsimaupjftxml
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true